### ISSUE TITLE
 Humann3 does not finish running, bowtie2 error

### ISSUE THREAD

**Issue by SSRAJ017** [vdblab/vdblab-pipelines#90]
Intermediate step in humann3 using bowtie2 throws error:
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
LANGUAGE = (unset),
LC_ALL = (unset),
LANG = "en_US.UTF-8"
are supported and installed on your system.perl: warning: Falling back to the standard locale ("C")
Error while flushing and closing output
terminate called after throwing an instance of 'int'
(ERR): bowtie2-align died with signal 6 (ABRT) (core dumped)

Likely insufficient memory

**Comment by nickp60** [comment]
I think this is resolved after bumping the version of RGI. Feel free to reopen if you run into the issue again.
